-- MIGRATION SCRIPT FROM 2.3 TO 2.4

-- NOTIFICATION are not entities
DROP TABLE KKB_NOTIFICATION;

/*
 * VERSION TABLE
 */
DROP TABLE KKB_VER_2_3;
CREATE TABLE KKB_VER_2_4 (DUMMY INTEGER NOT NULL, PRIMARY KEY (DUMMY));
