-- MIGRATION SCRIPT FROM 4.0.4 TO 5

-- PAYMENT CANCELATION

ALTER TABLE PAYMENT
	ADD COLUMN CANCELATION_REASON VARCHAR(255) AFTER AMOUNT,
	ADD COLUMN CANCELED DATETIME AFTER CANCELATION_REASON; 

/*
 * VERSION TABLE
 */
DROP TABLE EPAYMENT_VER_4_0_4;
CREATE TABLE EPAYMENT_VER_5 (DUMMY INTEGER NOT NULL, PRIMARY KEY (DUMMY));
