-- MIGRATION SCRIPT FROM 4.0 TO 4.0.3


-- payer name field moving
ALTER TABLE PAYMENT ADD COLUMN PAYER_NAME VARCHAR(255) AFTER CURRENCY;
UPDATE PAYMENT SET PAYMENT.PAYER_NAME = SELECT PAYER_NAME FROM QAZKOM_PAYMENT WHERE PAYMENT.ID = QAZKOM_PAYMENT.ID; 
ALTER TABLE QAZKOM_PAYMENT DROP COLUMN PAYER_NAME;

/*
 * VERSION TABLE
 */
DROP TABLE EPAYMENT_VER_4_0;
CREATE TABLE EPAYMENT_VER_4_0_3 (DUMMY INTEGER NOT NULL, PRIMARY KEY (DUMMY));
